---
title: "Gradescope Autograder Tutorial with R"
author: Danny Klinenberg^[University of California, Santa Barbara. Special thanks to Victor Huang and Zihao Zheng for their tireless work on the development and implementation. For the latest version, click [here](https://github.com/datawranglingUCSBecon/autograder_template).]
date: "Last Updated: `r Sys.Date()`"
output: 
  pdf_document:
    highlight: haddock
    toc: true
    number_sections: true
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancypagestyle{plain}{\pagestyle{fancy}}
  - \fancyhead[LE, LO]{Econ 145 - Fall 2020}
  - \fancyfoot[LE,LO]{Copyright UCSB 2020}
  - \usepackage[fontsize=12pt]{scrextend}
  - \usepackage{setspace}\doublespacing
  - \usepackage{pdfpages}
  - \usepackage{caption}
  - \usepackage{xcolor}
  - \newcommand{\magenta}[1]{\textcolor{magenta}{#1}}
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=50),tidy=TRUE)
library(png)
library(tidyverse)
library(knitr)
library(kableExtra)
```

\newpage

```{r, child="01-intro.Rmd"}
#Introduction
```

```{r, child="02-setup.Rmd"}
# Basic Setup
```

```{r, child="03-how_to.Rmd"}

```

```{r, child="04-step.Rmd"}

```

```{r, child="05-writing.Rmd"}

```

```{r, child="06-troubleshoo.Rmd"}

```

```{r, child="07-build_inf.Rmd"}

```

```{r, child="07-appendix.Rmd"}

```
