---
title: "Homework Template: Strings and Debugging"
author: "Econ 145: Data Wrangling in R"
output: pdf_document
header-includes:
  - \usepackage{xcolor}
  - \newcommand{\magenta}[1]{\textcolor{magenta}{#1}}
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Standarized things:

* All variable names should be in lower case and have underscores for spaces (e.g. $\color{magenta}{\text{data\_frame}}$ )

* For variables that students need to save for gradescope to be saved, use     $\color{magenta}{\text{variable\_name}}$

* Homeworks should generally take around 5-8 hours. Aim on the shorter rather than longer side.

* Referring to functions should be written as `mean` function.

* Referrring to packages should be done as `tidyverse` package.

Template of homework is given below.



# Overview

Describe the data set and why it is important. Be sure to include anything that is unique to the data.

## To Receive Credit

* Save the .R file as $\color{blue}{\text{assignment\_2}}$. Make sure your capitalization is correct as the autograder is case-sensitive.

* Be sure to include your first name, last name, and perm number on your one-page writeup.

* Your one-page writeup must be submitted in a .pdf to receive credit.




# Part 1: Coding Assignment

1. Skill they are using or question they are answering

    a) Coding question.
    b) Coding question.
    c) Coding question.
    
2. Another skill or question they are attempting

    a) Coding question.
    b) Coding question.
    c) Coding question.
    
3. Final question: * Save the .R file as $\color{blue}{\text{assignment\_2.R}}$

# Part 2: Write-up

Come up with a reason to use the data set in the real world. Describe a problem at hand and encourage the students to solve it. Be sure to include at least a few bullet points of things they should answer in their write up so that we can create a grading rubric around it. For instance,

* Summary statistics of the average X and Y.

* What is the most frequent X and why do you think this is? Is there more data to support this hypothesis?

* At least 1 graph explaining X.

* Save the .R file as $\color{blue}{\text{assignment\_2.pdf}}$

We can have an objective grading portion on including these things, while having a subjective portion that includes presentation and writing.

