---
title: "Homework Rubric Template"
subtitle: "Econ 145: Data Wrangling in R"
author: "Michael Topper"
output: pdf_document
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancypagestyle{plain}{\pagestyle{fancy}}
  - \fancyhead[LE, LO]{Econ 145 - Fall 2020}
  - \fancyfoot[LE,LO]{Copyright UCSB 2020}
  - \newcommand{\magenta}[1]{\textcolor{magenta}{#1}}
  - \usepackage{xcolor}
urlcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F)
library(tidyverse)
library(janitor)
library(lubridate)
```

# Rubric

Some general advice for the TAs writing the TAs.

* Assignment Total Points: 100

* Coding Portion Points: 65

* Write up: 35

## Part 1: Coding Portion

1. (6 points) Points are awarded on an all-or-nothing scale. The students must have 3 tibbles (or data frames) with these names and their variable names cleaned with `clean_names` from the `janitor` package. 
2. (9 points)

    a) (3 points) Must have correct primary key of "players"
    b) (3 points) 1 point awarded for each correct key they have. I believe they need 3 keys to uniquely identify. My keys I have are: "name", "year_start", "weight", "height", "college"
    c) (3 points) 1 point awarded for each correct key they have *in addition to* the player key. For instance, they need to have "year", "age", and "tm" to get full credit.. 
    
    
3. (25 points)

    a) (4 points) 1 point for each column correct.
    b) (7 points) Graded by TA. Graph must be a histogram of ppg (2 points), contain a red dashed vline (2 points), axis labeled (2 points), and title (1 point).
    c) (3 points) 3 points for the correct answer.
    d) (3 points) 3 points for the correct tibble/data frame. 
    e) (4 points) 4 points for correct answer.
    f) (4 points) 4 points for correct answer.
    
4. (25 points) All of this question is all-or-nothing.

    a) (5 points)
    b) (5 points)
    c) (5 points)
    d) (5 points)
    e) (5 points)
    
5. (No points) This is only here for instructional purposes. 

## Part 2: Write up

There are two portions to this write up:

* 2c from previous portion which is worth 7 points. (see above)
* The written portion which is worth 35 points.

Components to be graded:

* (10 points) Includes at least 1 other graph explaining how at least one (e.g. Kobe, Lebron, or Jordan) are outstanding for their time period. 

  + (minus 2 point) If the graph has no axis or title.
  + (minus 2 points) If the graph is not clear at all.
  + (minus 1 point) If the graph is a subset of the 2c graph (e.g. they did the same graph but filtered for the player of choice)

* (10 points) Includes a statistical comparison between Kobe, Jordan, and Lebron. This can anything from best points per game, assists per game, highest scoring games etc. All evidence must come from the data.
  + (minus 5 points) If their writing contains significant grammatical errors and is difficult to understand.
  + (minus 5 points) If they provide no comparison using statistical analysis. 

* (5 points) Overall presentation (e.g. logical flow, polish)
* (10 points) For completion. 
