#!/usr/bin/env bash
cp /autograder/submission/test.R /autograder/source/test.R

cd /autograder/source

git clone https://datawranglingUCSBecon:autograder1234@github.com/datawranglingUCSBecon/autograderecon

cp autograderecon/helper_functions/JSONmaker.R /autograder/source/JSONmaker.R
cp autograderecon/helper_functions/setup.R /autograder/source/setup.R
cp autograderecon/helper_functions/packages.R /autograder/source/packages.R
cp autograderecon/hw_template/autograder_setup.R /autograder/source/autograder_setup.R

cp autograderecon/2020_f_psexample_v1/DGP.R /autograder/source/DGP.R
cp autograderecon/2020_f_psexample_v1/inputs.R /autograder/source/inputs.R
cp autograderecon/2020_f_psexample_v1/MasterData.csv /autograder/source/MasterData.csv

Rscript autograderecon/2020_f_psexample_v1/autograde.R
